# Generated by Django 2.0.2 on 2018-03-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
